#!/bin/bash
#
# This file sets up the yocto build environment for the libipho platform.
#

BUILD_MESSAGE() {
  echo ""
  echo "The build environment for the libipho platform has been set up."
  echo "Please run"
  echo "    'bitbake libipho-image'"
  echo "in order to bulid the image for the SD-card of the libipho platform."
  echo ""
}

BASE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

##############################################################
# Make sure that the submodules are initialized
##############################################################
git submodule status --recursive | grep -q "^-"
SUBMODULE_STATUS=$?
if [ "${SUBMODULE_STATUS}" = "0" ]; then
  echo "Submodules are not initialized. I will do that now..."
  git submodule update --init --recursive
fi

source ${BASE_PATH}/sources/poky/oe-init-build-env ${BASE_PATH}/build

##############################################################
# Check whether we have already modified the local.conf file
# in order to avoid changing it again
##############################################################
LOCAL_CONF_PATH=${BASE_PATH}/build/conf/local.conf
BBLAYERS_CONF_PATH=${BASE_PATH}/build/conf/bblayers.conf
LIBIPHO_LOCAL_CONF_TOKEN="# LIBIPHO_LOCAL_CONF"
LOCAL_CONF_IS_ADAPTED=`grep "${LIBIPHO_LOCAL_CONF_TOKEN}" ${LOCAL_CONF_PATH}`
if [ -n "${LOCAL_CONF_IS_ADAPTED}" ]; then
  echo "local.conf has already been adapted."
  echo "However, if you change the bootstrap script, make sure that you"
  echo "also delete the file ${LOCAL_CONF_PATH} in order to make sure"
  echo "that your changes are taken into account."

  BUILD_MESSAGE

  return
fi

##############################################################
# Modify local.conf file
##############################################################

APPEND_LOCAL_CONF()
{
  echo $1 >> ${LOCAL_CONF_PATH}
}

APPEND_LOCAL_CONF ""
APPEND_LOCAL_CONF "${LIBIPHO_LOCAL_CONF_TOKEN}"
APPEND_LOCAL_CONF ""
APPEND_LOCAL_CONF "MACHINE     = \"beaglebone\""
APPEND_LOCAL_CONF "DL_DIR      = \"${HOME}/yocto/downloads\""
APPEND_LOCAL_CONF "SSTATE_DIR  = \"${HOME}/yocto/sstate-cache\""
APPEND_LOCAL_CONF "DISTRO      = \"libipho\""
APPEND_LOCAL_CONF "INHERIT    += \"rm_work\""
APPEND_LOCAL_CONF "DEPLOY_DIR  = \"${BASE_PATH}/deploy\""
# Remove debug tweaks in order to remove the root login without password
sed -i 's:EXTRA_IMAGE_FEATURES = "debug-tweaks":#EXTRA_IMAGE_FEATURES = "debug-tweaks":g' ${LOCAL_CONF_PATH}

##############################################################
# Overwrite bblayers.conf
##############################################################

cat <<EOF > ${BBLAYERS_CONF_PATH}
# WARNING: This file is automatically generated by the
# boostrap.sh script of the libipho-platform project.
# Any changes to this file may be overwritten by
# a subsequent call to the bootstrap.sh script.
#
# LAYER_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
LCONF_VERSION = "6"

BBPATH = "\${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \\
  \${BBPATH}/../sources/poky/meta \\
  \${BBPATH}/../sources/poky/meta-yocto \\
  \${BBPATH}/../sources/poky/meta-yocto-bsp \\
  \${BBPATH}/../sources/meta-openembedded/meta-oe \\
  \${BBPATH}/../sources/meta-libipho \\
  "
BBLAYERS_NON_REMOVABLE ?= " \\
  ${BBPATH}/../sources/poky/meta \\
  ${BBPATH}/../sources/poky/meta-yocto \\
  "
EOF

BUILD_MESSAGE
